name: DyedBackpacks
version: ${project.version}
author: TheBusyBiscuit

description: A Slimefun Addon that adds dyed backpacks
website: https://github.com/TheBusyBiscuit/DyedBackpacks

main: io.github.thebusybiscuit.dyedbackpacks.DyedBackpacks
depend: [Slimefun]

api-version: 1.14